name: Tourism Package Purchase Prediction pipeline

on:
  push:
    branches:
      - main

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: Tourism_Package_Purchase_Prediction/requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r Tourism_Package_Purchase_Prediction/requirements.txt
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Tourism_Package_Purchase_Prediction/model_building/data_register.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: Tourism_Package_Purchase_Prediction/requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r Tourism_Package_Purchase_Prediction/requirements.txt
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Tourism_Package_Purchase_Prediction/model_building/prep.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: Tourism_Package_Purchase_Prediction/requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r Tourism_Package_Purchase_Prediction/requirements.txt

      # Optional and generally unnecessary in CI since it won't be reachable
      # - name: Start MLflow UI (optional)
      #   run: |
      #     nohup mlflow ui --host 127.0.0.1 --port 5000 & 
      #     sleep 5

      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # If using a remote MLflow tracking server, set:
          # MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: python Tourism_Package_Purchase_Prediction/model_building/train.py

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: [model-training, data-prep, register-dataset]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: Tourism_Package_Purchase_Prediction/requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r Tourism_Package_Purchase_Prediction/requirements.txt
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Tourism_Package_Purchase_Prediction/hosting/hosting.py
