name: Tourism Package Purchase Prediction pipeline
on:
  push:
    branches:
      - main  # Automatically triggers on push to the main branch

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Tourism_Package_Purchase_Prediction/model_building/data_register.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r Tourism_Package_Purchase_Prediction/requirements.txt
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Tourism_Package_Purchase_Prediction/model_building/prep.py

  model-training:  # 🔧 Fixed typo: was 'model-traning'
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r Tourism_Package_Purchase_Prediction/requirements.txt
      - name: Start MLflow Server
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &  # 🔧 Fixed HTML entity &amp; to &
          sleep 5  # Wait for a moment to let the server start
      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Tourism_Package_Purchase_Prediction/model_building/train.py

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: [model-training, data-prep, register-dataset]  # 🔧 Updated job name to match corrected one
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r Tourism_Package_Purchase_Prediction/requirements.txt
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Tourism_Package_Purchase_Prediction/hosting/hosting.py
