name: Tourism Package Purchase Prediction pipeline

on: push: branches: [ main ]

permissions: contents: write # needed for optional auto-commit step

concurrency: group: tourism-pipeline-${{ github.ref }} cancel-in-progress: true

defaults: run: shell: bash working-directory: Tourism_Package_Purchase_Prediction

jobs:

register-dataset: runs-on: ubuntu-latest steps: - uses: actions/checkout@v4

  - uses: actions/setup-python@v5
    with:
      python-version: '3.9'
      cache: 'pip'
      cache-dependency-path: |
        **/requirements.txt
        **/pyproject.toml

  - name: Install Dependencies
    run: |
      set -euo pipefail
      REQ_PATH="$(git ls-files | grep -E '(^|/)requirements\.txt$' | head -n1 || true)"
      if [ -z "$REQ_PATH" ]; then
        echo "requirements.txt not found"; exit 1
      fi
      python -m pip install --upgrade pip
      python -m pip install -r "$REQ_PATH"

  - name: Upload dataset to Hugging Face Hub
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    run: python model_building/data_register.py
