# .github/workflows/pipeline.yml
name: Tourism Package Purchase Prediction pipeline

on:
  push:
    branches: [ main ]

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Uncomment for a one-time sanity check of your workspace
      # - name: Show workspace layout
      #   run: |
      #     pwd
      #     ls -la
      #     echo "---- recursive ----"
      #     ls -R | sed -n '1,200p'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'         # <-- PINNED to 3.9
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python model_building/data_register.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python model_building/prep.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Optional: MLflow UI (not accessible from GitHub runner, so generally skip)
      # - name: Start MLflow UI (optional)
      #   run: |
      #     nohup mlflow ui --host 127.0.0.1 --port 5000 & 
      #     sleep 5

      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}  # if you use a remote server
        run: python model_building/train.py

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: [model-training, data-prep, register-dataset]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python hosting/hosting.py
